// Which zod schema describes which gateway response. The key is the real unit of
// the contract — "METHOD path" exactly as docs/openapi.json spells it — because
// the Pydantic names carry a `Response` suffix and cannot be matched by name.
//
// Every JSON route belongs to exactly ONE bucket; routes.test.ts fails otherwise,
// so a new route cannot be added without a decision about its schema.
import type { z } from 'zod'
import { ChatList, MessageReply, Transcript } from './chat.ts'
import {
  Connection,
  ConnectionExposure,
  ConnectionGroups,
  ConnectionList,
  ConnectionPairing,
  PairingCodeIssued,
} from './connection.ts'
import {
  LiveConfigList,
  LiveConfigSaved,
  LlmConfigList,
  LlmConfigSaved,
  PingResult,
  ProviderCatalog,
} from './llm.ts'
import { TaskRules } from './permission.ts'
import { Ok } from './primitives.ts'
import { ProfileEnvelope, ProfileList } from './profile.ts'
import { SecretList, SecretSaved } from './secret.ts'
import { MemoryDoc, ProfileHealth } from './settings.ts'
import {
  InquiryList,
  NewTaskEnvelope,
  RunDetailEnvelope,
  RunList,
  TaskEnvelope,
  TaskList,
} from './task.ts'
import {
  CodexLoginUrl,
  CodexStatus,
  CodingAgents,
  CodingCatalog,
  FsListing,
  FsMkdirResult,
  GoogleLoginUrl,
  GoogleStatus,
  Health,
  IdentitySeeded,
  OkOrError,
  StatusList,
  Usage,
  UsageRollup,
} from './system.ts'

export const ROUTES: Record<string, z.ZodTypeAny> = {
  'GET /api/health': Health,
  'GET /api/usage': UsageRollup,
  'GET /api/status': StatusList,
  'GET /api/p/{pid}/health': ProfileHealth,
  'GET /api/p/{pid}/usage': Usage,
  'GET /api/coding/agents': CodingAgents,
  'GET /api/coding/{agent}/models': CodingCatalog,
  'GET /api/fs/list': FsListing,
  'POST /api/fs/mkdir': FsMkdirResult,
  'GET /api/memory': MemoryDoc,
  'POST /api/memory': Ok,
  'GET /api/p/{pid}/memory': MemoryDoc,
  'POST /api/p/{pid}/memory': Ok,
  'POST /api/identity': IdentitySeeded,
  'POST /api/onboarded': Ok,
  'GET /api/p/{pid}/chats': ChatList,
  'GET /api/p/{pid}/chats/{chat_id}': Transcript,
  'PATCH /api/p/{pid}/chats/{chat_id}': Ok,
  'DELETE /api/p/{pid}/chats/{chat_id}': Ok,
  'POST /api/p/{pid}/message': MessageReply,
  'GET /api/p/{pid}/tasks': TaskList,
  'POST /api/p/{pid}/tasks': NewTaskEnvelope,
  'GET /api/p/{pid}/tasks/{task_id}': TaskEnvelope,
  'PATCH /api/p/{pid}/tasks/{task_id}': TaskEnvelope,
  'DELETE /api/p/{pid}/tasks/{task_id}': Ok,
  'POST /api/p/{pid}/tasks/{task_id}/run': RunDetailEnvelope,
  'GET /api/p/{pid}/tasks/{task_id}/runs': RunList,
  'GET /api/p/{pid}/tasks/{task_id}/permissions': TaskRules,
  'DELETE /api/p/{pid}/tasks/{task_id}/permissions': Ok,
  'GET /api/p/{pid}/runs/{run_id}': RunDetailEnvelope,
  'POST /api/p/{pid}/runs/{run_id}/stop': Ok,
  'POST /api/p/{pid}/runs/{run_id}/seen': Ok,
  'GET /api/p/{pid}/inquiries/pending': InquiryList,
  'POST /api/p/{pid}/inquiries/{inquiry_id}/answer': Ok,
  'GET /api/llm-configs': LlmConfigList,
  'GET /api/llm-configs/models': ProviderCatalog,
  'POST /api/llm-configs': LlmConfigSaved,
  'POST /api/llm-configs/test': PingResult,
  'POST /api/llm-configs/{cid}': LlmConfigSaved,
  'DELETE /api/llm-configs/{cid}': Ok,
  'POST /api/llm-configs/{cid}/use': Ok,
  'POST /api/llm-configs/{cid}/test': PingResult,
  'GET /api/live-configs': LiveConfigList,
  'POST /api/live-configs': LiveConfigSaved,
  'POST /api/live-configs/test': PingResult,
  'POST /api/live-configs/{cid}': LiveConfigSaved,
  'DELETE /api/live-configs/{cid}': Ok,
  'POST /api/live-configs/{cid}/use': Ok,
  'POST /api/live-configs/{cid}/test': PingResult,
  'GET /api/secrets': SecretList,
  'POST /api/secrets': SecretSaved,
  'POST /api/secrets/key': Ok,
  'POST /api/secrets/{sid}': SecretSaved,
  'DELETE /api/secrets/{sid}': Ok,
  'GET /api/google/status': GoogleStatus,
  'POST /api/google/credentials': OkOrError,
  'POST /api/google/login_url': GoogleLoginUrl,
  'POST /api/google/logout': Ok,
  'GET /api/codex/status': CodexStatus,
  'POST /api/codex/login_url': CodexLoginUrl,
  'POST /api/codex/submit': Ok,
  'POST /api/codex/logout': Ok,
  'GET /api/profiles': ProfileList,
  'POST /api/profiles': ProfileEnvelope,
  'POST /api/profiles/{pid}': ProfileEnvelope,
  'DELETE /api/profiles/{pid}': Ok,
  'POST /api/profiles/{pid}/restore': ProfileEnvelope,
  'GET /api/connections': ConnectionList,
  // The three writes below answer with the one Connection they changed, not the
  // list — Settings re-renders that row from the response.
  'POST /api/connections': Connection,
  'POST /api/connections/{cid}': Connection,
  'POST /api/connections/{cid}/token': Connection,
  'DELETE /api/connections/{cid}': Ok,
  'POST /api/connections/{cid}/default': Connection,
  'GET /api/connections/{cid}/exposure': ConnectionExposure,
  'POST /api/connections/{cid}/exposure': ConnectionExposure,
  'GET /api/connections/{cid}/pairing': ConnectionPairing,
  'POST /api/connections/{cid}/pairing': ConnectionPairing,
  'DELETE /api/connections/{cid}/pairing/{key}': ConnectionPairing,
  // Alone among the pairing routes: the minted code, not the roster around it.
  'POST /api/connections/{cid}/pairing/code': PairingCodeIssued,
  'GET /api/connections/{cid}/groups': ConnectionGroups,
  'POST /api/connections/{cid}/groups/{chat_id}/profile': ConnectionGroups,
}

// No schema by design — the reason is the point of the entry.
export const UNMAPPED: Record<string, string> = {
  'GET /api/p/{pid}/files/raw': 'FileResponse — raw file bytes, not JSON',
  'POST /api/p/{pid}/voice/preview': 'audio/wav',
  'GET /api/google/callback': 'HTMLResponse — the OAuth redirect landing page',
  'GET /': 'RedirectResponse to /app/',
  'GET /app': 'serves the SPA',
  'GET /app/{path}': 'serves the SPA',
  'GET /{full_path}': 'catch-all: SPA redirect, or 404 for an unknown /api path',
  'GET /{name}.svg': 'FileResponse — image/svg+xml',
  'GET /favicon.ico': 'FileResponse',
  'GET /voices/{name}.wav': 'FileResponse — audio/wav',
  // The unmatched-/api/* write catch-all. It only ever answers a bare 404, so
  // there is no 200 body to describe.
  'DELETE /api/{full_path}': 'api_not_found — bare 404, no body',
  'PATCH /api/{full_path}': 'api_not_found — bare 404, no body',
  'POST /api/{full_path}': 'api_not_found — bare 404, no body',
  'PUT /api/{full_path}': 'api_not_found — bare 404, no body',
  // Mounted by assistant/hitl/desktop.py, not by the gateway's own route table:
  // the desktop HITL page posts to them itself, the SPA never does, so neither
  // has a zod twin to check against.
  'GET /hitl/{req_id}': 'HTMLResponse — the server-rendered HITL question page',
  'POST /hitl/{req_id}/answer': 'the HITL page posts to itself; not part of the SPA contract',
}

// Shrinks to {} as phases land; the value names the phase that will take it.
export const PENDING: Record<string, string> = {
  // --- phase 5: files, folders ---
  'GET /api/folders': 'phase 5',
  'POST /api/folders': 'phase 5',
  'POST /api/folders/{fid}': 'phase 5',
  'DELETE /api/folders/{fid}': 'phase 5',
  'POST /api/folders/{fid}/grants': 'phase 5',
  'DELETE /api/folders/{fid}/grants': 'phase 5',
  'GET /api/p/{pid}/folders/roots': 'phase 5',
  'GET /api/p/{pid}/files': 'phase 5',
  'GET /api/p/{pid}/files/search': 'phase 5',
  'GET /api/p/{pid}/files/mentions': 'phase 5',
  'POST /api/p/{pid}/files/upload': 'phase 5',
  'POST /api/p/{pid}/files/mkdir': 'phase 5',
  'POST /api/p/{pid}/files/move': 'phase 5',
  'PUT /api/p/{pid}/files/raw': 'phase 5',
  'DELETE /api/p/{pid}/files/raw': 'phase 5',
  // --- phase 6: skills, permissions ---
  'GET /api/skills': 'phase 6',
  'POST /api/skills/{name}/state': 'phase 6',
  'DELETE /api/skills/{name}': 'phase 6',
  'POST /api/skills/search': 'phase 6',
  'POST /api/skills/discover': 'phase 6',
  'POST /api/skills/discover-upload': 'phase 6',
  'POST /api/skills/install': 'phase 6',
  'POST /api/skills/install-upload': 'phase 6',
  'GET /api/p/{pid}/skills': 'phase 6',
  'POST /api/p/{pid}/skills/{name}/state': 'phase 6',
  'DELETE /api/p/{pid}/skills/{name}': 'phase 6',
  'POST /api/p/{pid}/skills/{name}/suppress': 'phase 6',
  'DELETE /api/p/{pid}/skills/{name}/suppress': 'phase 6',
  'POST /api/p/{pid}/skills/install': 'phase 6',
  'POST /api/p/{pid}/skills/install-upload': 'phase 6',
  'POST /api/p/{pid}/skills/discover': 'phase 6',
  'POST /api/p/{pid}/skills/discover-upload': 'phase 6',
  'GET /api/permissions': 'phase 6',
  'POST /api/permissions/commands': 'phase 6',
  'DELETE /api/permissions/commands': 'phase 6',
  // --- phase 7: settings, voice, hitl ---
  'GET /api/p/{pid}/settings': 'phase 7',
  'POST /api/p/{pid}/settings/mcp': 'phase 7',
  'DELETE /api/p/{pid}/settings/mcp/{name}': 'phase 7',
  'POST /api/p/{pid}/settings/mcp/{name}/health': 'phase 7',
  'POST /api/p/{pid}/settings/focuses': 'phase 7',
  'POST /api/p/{pid}/settings/llm-override': 'phase 7',
  'POST /api/p/{pid}/settings/live-override': 'phase 7',
  'POST /api/p/{pid}/settings/reply-timeout': 'phase 7',
  'POST /api/p/{pid}/settings/voice_provider': 'phase 7',
  'GET /api/p/{pid}/voice/voices': 'phase 7',
  'POST /api/p/{pid}/voice/select': 'phase 7',
  'GET /api/p/{pid}/hitl/pending': 'phase 7',
}
