// Which zod schema describes which gateway response. The key is the real unit of
// the contract — "METHOD path" exactly as docs/openapi.json spells it — because
// the Pydantic names carry a `Response` suffix and cannot be matched by name.
//
// Every JSON route belongs to exactly ONE bucket; routes.test.ts fails otherwise,
// so a new route cannot be added without a decision about its schema.
import type { z } from 'zod'
import { Ok } from './primitives.ts'
import { MemoryDoc, ProfileHealth } from './settings.ts'
import {
  CodingAgents,
  CodingCatalog,
  FsListing,
  FsMkdirResult,
  Health,
  IdentitySeeded,
  StatusList,
  Usage,
  UsageRollup,
} from './system.ts'

export const ROUTES: Record<string, z.ZodTypeAny> = {
  'GET /api/health': Health,
  'GET /api/usage': UsageRollup,
  'GET /api/status': StatusList,
  'GET /api/p/{pid}/health': ProfileHealth,
  'GET /api/p/{pid}/usage': Usage,
  'GET /api/coding/agents': CodingAgents,
  'GET /api/coding/{agent}/models': CodingCatalog,
  'GET /api/fs/list': FsListing,
  'POST /api/fs/mkdir': FsMkdirResult,
  'GET /api/memory': MemoryDoc,
  'POST /api/memory': Ok,
  'GET /api/p/{pid}/memory': MemoryDoc,
  'POST /api/p/{pid}/memory': Ok,
  'POST /api/identity': IdentitySeeded,
  'POST /api/onboarded': Ok,
}

// No schema by design — the reason is the point of the entry.
export const UNMAPPED: Record<string, string> = {
  'GET /api/p/{pid}/files/raw': 'FileResponse — raw file bytes, not JSON',
  'POST /api/p/{pid}/voice/preview': 'audio/wav',
  'GET /api/google/callback': 'HTMLResponse — the OAuth redirect landing page',
  'GET /': 'RedirectResponse to /app/',
  'GET /app': 'serves the SPA',
  'GET /app/{path}': 'serves the SPA',
  'GET /{full_path}': 'catch-all: SPA redirect, or 404 for an unknown /api path',
  'GET /{name}.svg': 'FileResponse — image/svg+xml',
  'GET /favicon.ico': 'FileResponse',
  'GET /voices/{name}.wav': 'FileResponse — audio/wav',
  // The unmatched-/api/* write catch-all. It only ever answers a bare 404, so
  // there is no 200 body to describe.
  'DELETE /api/{full_path}': 'api_not_found — bare 404, no body',
  'PATCH /api/{full_path}': 'api_not_found — bare 404, no body',
  'POST /api/{full_path}': 'api_not_found — bare 404, no body',
  'PUT /api/{full_path}': 'api_not_found — bare 404, no body',
  // Mounted by assistant/hitl/desktop.py, not by the gateway's own route table:
  // the desktop HITL page posts to them itself, the SPA never does, so neither
  // has a zod twin to check against.
  'GET /hitl/{req_id}': 'HTMLResponse — the server-rendered HITL question page',
  'POST /hitl/{req_id}/answer': 'the HITL page posts to itself; not part of the SPA contract',
}

// Shrinks to {} as phases land; the value names the phase that will take it.
export const PENDING: Record<string, string> = {
  // --- phase 2: tasks, runs, chats, inquiries, message ---
  'GET /api/p/{pid}/chats': 'phase 2',
  'GET /api/p/{pid}/chats/{chat_id}': 'phase 2',
  'PATCH /api/p/{pid}/chats/{chat_id}': 'phase 2',
  'DELETE /api/p/{pid}/chats/{chat_id}': 'phase 2',
  'POST /api/p/{pid}/message': 'phase 2',
  'GET /api/p/{pid}/tasks': 'phase 2',
  'POST /api/p/{pid}/tasks': 'phase 2',
  'GET /api/p/{pid}/tasks/{task_id}': 'phase 2',
  'PATCH /api/p/{pid}/tasks/{task_id}': 'phase 2',
  'DELETE /api/p/{pid}/tasks/{task_id}': 'phase 2',
  'POST /api/p/{pid}/tasks/{task_id}/run': 'phase 2',
  'GET /api/p/{pid}/tasks/{task_id}/runs': 'phase 2',
  'GET /api/p/{pid}/tasks/{task_id}/permissions': 'phase 2',
  'DELETE /api/p/{pid}/tasks/{task_id}/permissions': 'phase 2',
  'GET /api/p/{pid}/runs/{run_id}': 'phase 2',
  'POST /api/p/{pid}/runs/{run_id}/stop': 'phase 2',
  'POST /api/p/{pid}/runs/{run_id}/seen': 'phase 2',
  'GET /api/p/{pid}/inquiries/pending': 'phase 2',
  'POST /api/p/{pid}/inquiries/{inquiry_id}/answer': 'phase 2',
  // --- phase 3: llm-configs, live-configs, secrets, google, codex ---
  'GET /api/llm-configs': 'phase 3',
  'GET /api/llm-configs/models': 'phase 3',
  'POST /api/llm-configs': 'phase 3',
  'POST /api/llm-configs/test': 'phase 3',
  'POST /api/llm-configs/{cid}': 'phase 3',
  'DELETE /api/llm-configs/{cid}': 'phase 3',
  'POST /api/llm-configs/{cid}/use': 'phase 3',
  'POST /api/llm-configs/{cid}/test': 'phase 3',
  'GET /api/live-configs': 'phase 3',
  'POST /api/live-configs': 'phase 3',
  'POST /api/live-configs/test': 'phase 3',
  'POST /api/live-configs/{cid}': 'phase 3',
  'DELETE /api/live-configs/{cid}': 'phase 3',
  'POST /api/live-configs/{cid}/use': 'phase 3',
  'POST /api/live-configs/{cid}/test': 'phase 3',
  'GET /api/secrets': 'phase 3',
  'POST /api/secrets': 'phase 3',
  'POST /api/secrets/key': 'phase 3',
  'POST /api/secrets/{sid}': 'phase 3',
  'DELETE /api/secrets/{sid}': 'phase 3',
  'GET /api/google/status': 'phase 3',
  'POST /api/google/credentials': 'phase 3',
  'POST /api/google/login_url': 'phase 3',
  'POST /api/google/logout': 'phase 3',
  'GET /api/codex/status': 'phase 3',
  'POST /api/codex/login_url': 'phase 3',
  'POST /api/codex/submit': 'phase 3',
  'POST /api/codex/logout': 'phase 3',
  // --- phase 4: connections, profiles ---
  'GET /api/profiles': 'phase 4',
  'POST /api/profiles': 'phase 4',
  'POST /api/profiles/{pid}': 'phase 4',
  'DELETE /api/profiles/{pid}': 'phase 4',
  'POST /api/profiles/{pid}/restore': 'phase 4',
  'GET /api/connections': 'phase 4',
  'POST /api/connections': 'phase 4',
  'POST /api/connections/{cid}': 'phase 4',
  'POST /api/connections/{cid}/token': 'phase 4',
  'DELETE /api/connections/{cid}': 'phase 4',
  'POST /api/connections/{cid}/default': 'phase 4',
  'GET /api/connections/{cid}/exposure': 'phase 4',
  'POST /api/connections/{cid}/exposure': 'phase 4',
  'GET /api/connections/{cid}/pairing': 'phase 4',
  'POST /api/connections/{cid}/pairing': 'phase 4',
  'DELETE /api/connections/{cid}/pairing/{key}': 'phase 4',
  'POST /api/connections/{cid}/pairing/code': 'phase 4',
  'GET /api/connections/{cid}/groups': 'phase 4',
  'POST /api/connections/{cid}/groups/{chat_id}/profile': 'phase 4',
  // --- phase 5: files, folders ---
  'GET /api/folders': 'phase 5',
  'POST /api/folders': 'phase 5',
  'POST /api/folders/{fid}': 'phase 5',
  'DELETE /api/folders/{fid}': 'phase 5',
  'POST /api/folders/{fid}/grants': 'phase 5',
  'DELETE /api/folders/{fid}/grants': 'phase 5',
  'GET /api/p/{pid}/folders/roots': 'phase 5',
  'GET /api/p/{pid}/files': 'phase 5',
  'GET /api/p/{pid}/files/search': 'phase 5',
  'GET /api/p/{pid}/files/mentions': 'phase 5',
  'POST /api/p/{pid}/files/upload': 'phase 5',
  'POST /api/p/{pid}/files/mkdir': 'phase 5',
  'POST /api/p/{pid}/files/move': 'phase 5',
  'PUT /api/p/{pid}/files/raw': 'phase 5',
  'DELETE /api/p/{pid}/files/raw': 'phase 5',
  // --- phase 6: skills, permissions ---
  'GET /api/skills': 'phase 6',
  'POST /api/skills/{name}/state': 'phase 6',
  'DELETE /api/skills/{name}': 'phase 6',
  'POST /api/skills/search': 'phase 6',
  'POST /api/skills/discover': 'phase 6',
  'POST /api/skills/discover-upload': 'phase 6',
  'POST /api/skills/install': 'phase 6',
  'POST /api/skills/install-upload': 'phase 6',
  'GET /api/p/{pid}/skills': 'phase 6',
  'POST /api/p/{pid}/skills/{name}/state': 'phase 6',
  'DELETE /api/p/{pid}/skills/{name}': 'phase 6',
  'POST /api/p/{pid}/skills/{name}/suppress': 'phase 6',
  'DELETE /api/p/{pid}/skills/{name}/suppress': 'phase 6',
  'POST /api/p/{pid}/skills/install': 'phase 6',
  'POST /api/p/{pid}/skills/install-upload': 'phase 6',
  'POST /api/p/{pid}/skills/discover': 'phase 6',
  'POST /api/p/{pid}/skills/discover-upload': 'phase 6',
  'GET /api/permissions': 'phase 6',
  'POST /api/permissions/commands': 'phase 6',
  'DELETE /api/permissions/commands': 'phase 6',
  // --- phase 7: settings, voice, hitl ---
  'GET /api/p/{pid}/settings': 'phase 7',
  'POST /api/p/{pid}/settings/mcp': 'phase 7',
  'DELETE /api/p/{pid}/settings/mcp/{name}': 'phase 7',
  'POST /api/p/{pid}/settings/mcp/{name}/health': 'phase 7',
  'POST /api/p/{pid}/settings/focuses': 'phase 7',
  'POST /api/p/{pid}/settings/llm-override': 'phase 7',
  'POST /api/p/{pid}/settings/live-override': 'phase 7',
  'POST /api/p/{pid}/settings/reply-timeout': 'phase 7',
  'POST /api/p/{pid}/settings/voice_provider': 'phase 7',
  'GET /api/p/{pid}/voice/voices': 'phase 7',
  'POST /api/p/{pid}/voice/select': 'phase 7',
  'GET /api/p/{pid}/hitl/pending': 'phase 7',
}
