"""Response models for the gateway's JSON routes.

One module per domain, mirroring ``web/src/schemas/`` file for file, so the
front-end schema paired with a body is found by name. A model's module follows
its zod twin, not the rollout phase it landed in.

Naming: a whole HTTP response body takes the ``Response`` suffix
(``ProfileListResponse``); an entity nested inside a body takes ``Out``
(``UsageRowOut``).

Models inherit BaseModel directly: the model IS the contract, so a key it does
not declare does not reach the client. Completeness rests on the zod gate (a
field declared in zod and missing here fails CI), on the front end stripping
what its own schema omits, and on the per-phase body tests — not on letting
undeclared keys through.
"""

from .chat import (
    ChatListResponse,
    ChatRowOut,
    MessageResponse,
    TranscriptMessageOut,
    TranscriptResponse,
)
from .connection import (
    ConnectionExposureResponse,
    ConnectionGroupOut,
    ConnectionGroupsResponse,
    ConnectionListResponse,
    ConnectionOut,
    ConnectionPairingResponse,
    ConnectionSurfaceOut,
    GroupProfileOut,
    PairedAccountOut,
    PairingCodeIssuedResponse,
    PairingCodeOut,
    TokenStatusOut,
)
from .file import (
    FileRowOut,
    FilesListingResponse,
    FilesResponse,
    FolderDirOut,
    FolderFileOut,
    FolderListingResponse,
    MentionChatOut,
    MentionRowOut,
    MentionRunOut,
    MentionsResponse,
    MkdirResultResponse,
    SearchHitOut,
    SearchResultsResponse,
    UploadResultResponse,
    WriteResultResponse,
)
from .folder import (
    FolderConflictResponse,
    FolderListResponse,
    FolderMutatedResponse,
    FolderOut,
    FolderRootOut,
    FolderRootsResponse,
    FolderSavedResponse,
    GrantOut,
)
from .llm import (
    DepsStatusOut,
    KeySourceOut,
    LiveConfigListResponse,
    LiveConfigOut,
    LiveConfigSavedResponse,
    LiveKeySourceOut,
    LiveProviderOut,
    LlmConfigListResponse,
    LlmConfigOut,
    LlmConfigSavedResponse,
    LlmEnvOverrideOut,
    PingResultResponse,
    ProviderCatalogResponse,
)
from .permission import (
    PermissionMutatedResponse,
    PermissionSnapshotResponse,
    TaskRulesResponse,
)
from .primitives import ERROR_RESPONSES, ErrorBody, Ok, SecretRefOut, SharedKeyOut
from .profile import ProfileEnvelopeResponse, ProfileListResponse, ProfileOut
from .secret import SecretListResponse, SecretOut, SecretSavedResponse
from .settings import (
    HealthChannelOut,
    HealthCheckOut,
    HealthMcpServerOut,
    ProfileHealthResponse,
)
from .skill import (
    DiscoveredSkillOut,
    ProfileSkillInstalledResponse,
    ProfileSkillListResponse,
    ProfileSkillMutatedResponse,
    ProfileSkillOut,
    SkillDiscoveredResponse,
    SkillInstalledResponse,
    SkillListResponse,
    SkillMutatedResponse,
    SkillOut,
    SkillSearchHitOut,
    SkillSearchResultsResponse,
)
from .system import (
    CatalogModelOut,
    CodexLoginUrlResponse,
    CodexStatusResponse,
    CodingAgentOut,
    CodingAgentsResponse,
    CodingCatalogResponse,
    FsDirOut,
    FsListingErrorOut,
    FsListingOkOut,
    FsMkdirResponse,
    GoogleCredentialsErrorOut,
    GoogleCredentialsOkOut,
    GoogleLoginUrlErrorOut,
    GoogleLoginUrlOkOut,
    GoogleStatusResponse,
    HealthResponse,
    HealthStateOut,
    IdentitySeededResponse,
    MemoryDocResponse,
    StatusRowOut,
    UsageResponse,
    UsageRollupResponse,
    UsageRowOut,
    UsageTotalsOut,
)
from .task import (
    InquiryListResponse,
    InquiryOut,
    NewTaskEnvelopeResponse,
    RunDetailEnvelopeResponse,
    RunDetailOut,
    RunListResponse,
    RunOut,
    RunStatusOut,
    ScheduleOut,
    TaskEnvelopeResponse,
    TaskListResponse,
    TaskOut,
    TaskWithRunsOut,
)

__all__ = [
    "CatalogModelOut",
    "ChatListResponse",
    "ChatRowOut",
    "CodexLoginUrlResponse",
    "CodexStatusResponse",
    "CodingAgentOut",
    "CodingAgentsResponse",
    "CodingCatalogResponse",
    "ConnectionExposureResponse",
    "ConnectionGroupOut",
    "ConnectionGroupsResponse",
    "ConnectionListResponse",
    "ConnectionOut",
    "ConnectionPairingResponse",
    "ConnectionSurfaceOut",
    "DepsStatusOut",
    "DiscoveredSkillOut",
    "ERROR_RESPONSES",
    "ErrorBody",
    "FileRowOut",
    "FilesListingResponse",
    "FilesResponse",
    "FolderConflictResponse",
    "FolderDirOut",
    "FolderFileOut",
    "FolderListResponse",
    "FolderListingResponse",
    "FolderMutatedResponse",
    "FolderOut",
    "FolderRootOut",
    "FolderRootsResponse",
    "FolderSavedResponse",
    "FsDirOut",
    "FsListingErrorOut",
    "FsListingOkOut",
    "FsMkdirResponse",
    "GoogleCredentialsErrorOut",
    "GoogleCredentialsOkOut",
    "GoogleLoginUrlErrorOut",
    "GoogleLoginUrlOkOut",
    "GoogleStatusResponse",
    "GrantOut",
    "GroupProfileOut",
    "HealthChannelOut",
    "HealthCheckOut",
    "HealthMcpServerOut",
    "HealthResponse",
    "HealthStateOut",
    "IdentitySeededResponse",
    "InquiryListResponse",
    "InquiryOut",
    "KeySourceOut",
    "LiveConfigListResponse",
    "LiveConfigOut",
    "LiveConfigSavedResponse",
    "LiveKeySourceOut",
    "LiveProviderOut",
    "LlmConfigListResponse",
    "LlmConfigOut",
    "LlmConfigSavedResponse",
    "LlmEnvOverrideOut",
    "MemoryDocResponse",
    "MentionChatOut",
    "MentionRowOut",
    "MentionRunOut",
    "MentionsResponse",
    "MessageResponse",
    "MkdirResultResponse",
    "NewTaskEnvelopeResponse",
    "Ok",
    "PairedAccountOut",
    "PairingCodeIssuedResponse",
    "PairingCodeOut",
    "PermissionMutatedResponse",
    "PermissionSnapshotResponse",
    "PingResultResponse",
    "ProfileEnvelopeResponse",
    "ProfileHealthResponse",
    "ProfileListResponse",
    "ProfileOut",
    "ProfileSkillInstalledResponse",
    "ProfileSkillListResponse",
    "ProfileSkillMutatedResponse",
    "ProfileSkillOut",
    "ProviderCatalogResponse",
    "RunDetailEnvelopeResponse",
    "RunDetailOut",
    "RunListResponse",
    "RunOut",
    "RunStatusOut",
    "ScheduleOut",
    "SearchHitOut",
    "SearchResultsResponse",
    "SecretListResponse",
    "SecretOut",
    "SecretRefOut",
    "SecretSavedResponse",
    "SharedKeyOut",
    "SkillDiscoveredResponse",
    "SkillInstalledResponse",
    "SkillListResponse",
    "SkillMutatedResponse",
    "SkillOut",
    "SkillSearchHitOut",
    "SkillSearchResultsResponse",
    "StatusRowOut",
    "TaskEnvelopeResponse",
    "TaskListResponse",
    "TaskOut",
    "TaskRulesResponse",
    "TaskWithRunsOut",
    "TokenStatusOut",
    "TranscriptMessageOut",
    "TranscriptResponse",
    "UploadResultResponse",
    "UsageResponse",
    "UsageRollupResponse",
    "UsageRowOut",
    "UsageTotalsOut",
    "WriteResultResponse",
]
